refactor: move to atlas
satisfactorymodding/smr-api pull request #84
Opened 2024-08-15 20:04 UTC by Vilsol

2024-08-16 07:47 UTC, mircearoata requested changes
Both the GQL API and the REST mod all versions endpoint now return the mod ID in the mod_id field, which breaks SMM (both v2 and v3) and ficsit-cli (SMM v2 because it specifically uses getModByReference, and SMM v3/ficsit-cli because the lockfile will contain mod IDs instead of references for dependencies, but mod references for profile items).

For the custom index names on some of the types, do we actually need those? Since atlas didn't try to recreate them, it means they would simply get renamed, like the deleted_at indexes, so we'll have less custom indexes for stuff that's just a single-field unique.

2024-08-16 07:47 UTC, mircearoata commented on db/schema/mixin_time.go
Do we want these to be nullable, or is it just to match the existing schema?

2024-08-18 23:34 UTC, Vilsol commented on db/schema/version.go
> +		field.String("game_version").Optional(), // TODO Should be backfilled and turned non-optional
We can, but then we have 2 problems:

1. Many mods are with invalid constraints: https://gist.github.com/Vilsol/7e4fbcc59b0f4327f64382aac9d8d86a
2. What should we backfill the version with? `0`?

2024-08-18 23:36 UTC, Vilsol commented on db/schema/mixin_time.go
Not entirely sure why I set them to be nullable, prod DB has no fields with them being NULL

2024-08-18 23:38 UTC, Vilsol commented on db/schema/user.go
> +		index.Fields("facebook_id").StorageKey("idx_users_facebook_id"),
They were never unique in the first place, that was a mistake. Unique index would require them being set for every user.

2024-08-19 01:23 UTC, Vilsol commented on db/schema/version.go
> +		field.String("game_version").Optional(), // TODO Should be backfilled and turned non-optional
I have changed it so it gets backfilled with `0`'s

2024-08-19 01:24 UTC, Vilsol commented
I reverted back the change so `mod_id` now will return the `mod_reference` as before, added a deprecation notice to the field, and added a new `mod_reference` field that should be transitioned to as soon as this hits prod.

2024-08-19 04:54 UTC, mircearoata commented on db/schema/user.go
> +		index.Fields("facebook_id").StorageKey("idx_users_facebook_id"),
That wouldn't be the case, duplicate null values are considered distinct (at least by postgres), unless `NULLS NOT DISTINCT` is used on the index. https://www.postgresql.org/docs/current/indexes-unique.html#INDEXES-UNIQUE

2024-08-19 19:37 UTC, mircearoata approved these changes

2024-08-19 21:24 UTC, merged